# frozen_string_literal: true

module SlackSender
  class Configuration
    # Validated instance settings via the upstream Axn::Configurable DSL (class flavor).
    # Only the simple settings are declared here; everything bespoke below stays hand-written.
    extend Axn::Configurable::Settings

    # Per-class overrides (e.g. `sandbox_mode`) live under the :slack_sender namespace, reached via
    # `MyAction.configure(:slack_sender) { |c| c.sandbox_mode = false }` on any `use :slack` action.
    # Must precede any `overridable: true` setting.
    config_namespace :slack_sender
    overridable_config_source { SlackSender.config }

    SUPPORTED_ASYNC_BACKENDS = %i[sidekiq active_job].freeze
    SUPPORTED_SANDBOX_BEHAVIORS = %i[noop redirect passthrough].freeze

    # Slack's hard limit per file (1 GB)
    SLACK_MAX_FILE_SIZE = 1_073_741_824

    # Default file size threshold for async uploads
    DEFAULT_MAX_ASYNC_FILE_UPLOAD_SIZE = 26_214_400 # 25 MB

    setting :enabled, default: true
    setting :silence_archived_channel_exceptions
    setting :sandbox_default_behavior, default: :noop, one_of: SUPPORTED_SANDBOX_BEHAVIORS

    # Whether to autoload files in app/slack_notifiers under the SlackNotifiers namespace.
    # When true (default): app/slack_notifiers/foo.rb defines SlackNotifiers::Foo
    # When false: app/slack_notifiers/foo.rb defines Foo (standard Rails behavior)
    setting :use_slack_notifiers_namespace, default: true

    # Whether messages are redirected/suppressed for non-production. The Proc default is dynamic:
    # axn's Configurable re-derives it from Rails.env on every read while the setting is unset. An
    # explicit true/false wins; an explicit nil resets to the default (custom writer below). Marked
    # overridable so an individual action can opt in/out of sandbox for its own sends via
    # `configure(:slack_sender)` (resolved in the strategy and threaded down to DeliveryAxn).
    setting :sandbox_mode,
            default: -> { defined?(Rails) && Rails.respond_to?(:env) ? !Rails.env.production? : true },
            overridable: true

    # nil is a documented value (`Boolean or nil`) meaning "use the default". The DSL writer would
    # store an explicit nil as-is, making `sandbox_mode?` return `!!nil == false` and silently
    # disabling sandbox in non-production. Treat an assigned nil as a reset to the dynamic default
    # (remove the ivar so the Proc default re-derives), matching the pre-DSL hand-written reader.
    def sandbox_mode=(value)
      if value.nil?
        remove_instance_variable(:@sandbox_mode) if instance_variable_defined?(:@sandbox_mode)
      else
        @sandbox_mode = value
      end
    end

    def initialize
      # Bespoke settings (not backed by the DSL) need their defaults set here.
      @max_async_file_upload_size = DEFAULT_MAX_ASYNC_FILE_UPLOAD_SIZE
    end

    # `sandbox_mode?` is generated by the Axn::Configurable DSL (predicate reader, PRO-2888) as
    # `!!sandbox_mode`; it remains the public API used throughout the codebase.

    # Returns [found, value] for the per-class `name` override declared via `configure(:slack_sender)`
    # on `origin` (or the nearest ancestor), found=false when none. Reads axn's per-class override
    # store directly: axn exposes resolution (`resolve_override_for`) but not presence, and the
    # delivery path must diverge from global config *only* when an action actually opted in.
    def self.class_override(origin, name)
      return [false, nil] unless origin.is_a?(Module)

      klass = origin
      while klass.is_a?(Module)
        if klass.instance_variable_defined?(:@_axn_config_overrides)
          slot = klass.instance_variable_get(:@_axn_config_overrides)[config_namespace]
          return [true, slot[name]] if slot&.key?(name)
        end
        break unless klass.is_a?(Class) && klass.superclass

        klass = klass.superclass
      end
      [false, nil]
    end

    def async_backend
      @async_backend ||= detect_default_async_backend
    end

    def async_backend=(value)
      if value && !SUPPORTED_ASYNC_BACKENDS.include?(value)
        raise ArgumentError,
              "Unsupported async backend: #{value.inspect}. " \
              "Supported backends: #{SUPPORTED_ASYNC_BACKENDS.inspect}. " \
              "Please update SlackSender to support this backend."
      end

      @async_backend = value
    end

    def async_backend_available?
      backend = async_backend
      return false unless backend

      case backend
      when :sidekiq
        defined?(Sidekiq::Job)
      when :active_job
        defined?(ActiveJob::Base)
      else
        false
      end
    end

    # Maximum total file size allowed for async uploads.
    # Set to nil to disable (only Slack's 1 GB per-file limit applies).
    # Files exceeding this raise an error immediately to avoid blocking web processes.
    # Default: 25 MB
    attr_reader :max_async_file_upload_size

    def max_async_file_upload_size=(value)
      validate_max_async_file_upload_size!(value)
      @max_async_file_upload_size = value
    end

    private

    def validate_max_async_file_upload_size!(value)
      return if value.nil? # nil means disabled

      raise ArgumentError, "max_async_file_upload_size must be a non-negative integer or nil, got: #{value.inspect}" unless value.is_a?(Integer) && value >= 0

      return unless value > SLACK_MAX_FILE_SIZE

      raise ArgumentError,
            "max_async_file_upload_size (#{value}) cannot exceed Slack's maximum file size (#{SLACK_MAX_FILE_SIZE} bytes / 1 GB)"
    end

    def detect_default_async_backend
      return :sidekiq if defined?(Sidekiq::Job)
      return :active_job if defined?(ActiveJob::Base)

      nil
    end
  end

  class << self
    def config = @config ||= Configuration.new

    def configure
      self.config ||= Configuration.new
      yield(config) if block_given?
    end
  end
end
